### PR TITLE
Toasts replaced alerts and UI improved

### PR DESCRIPTION
**Pull request by Anikaaasingh**

### CODE REVIEW

**Comment by Anikaaasingh** [comment]
@Harsh-Singh-Rajput I have resolved the alert issue. Kindly merge my PR asap.

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput I have resolved the alert issue. Kindly merge my PR asap.
Nice work @Anikaaasingh , Can you also made implement Toast to save button then it will be perfectly match with the other buttons

**Comment by Anikaaasingh** [comment]
Ok I will  try and update you as soon as I finish it

**Comment by Anikaaasingh** [comment]
@Harsh-Singh-Rajput  I have done the required task. Kindly merge the PR.

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput I have done the required task. Kindly merge the PR.

There is a bug while aborting the save operation it shows both the toasts , there is no need to hurry take your time and then make request

**Comment by Anikaaasingh** [comment]
Actually, I tried it yesterday also but when I inserted toasts inside if loop it didn't show up and when I inserted it outside the loop then both are showing up. That's why I didn't do it yesterday.

**Comment by Anikaaasingh** [comment]
@Harsh-Singh-Rajput I guess the bug is resolved now.

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput I guess the bug is resolved now.

yes i will merge it now

**Comment by Anikaaasingh** [comment]
Thank you 😊

**Comment by Harsh-Singh-Rajput** [comment]
Nice work

**Pull request merged**
