### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by manipta**
all good just minor mistake string should be empty.
nice code btw.

### CODE REVIEW

**Comment by manipta** [comment]
hey forget to add my name in contributors. will there be any problem?

**Comment by Harsh-Singh-Rajput** [comment]
> all good just minor mistake string should be empty. nice code btw.

👍Nice Work .  Since you were the first to solve this issue I am merging your pull request :).
Happy Hacking, Happy Hactoberfest

**Comment by manipta** [comment]
Thank You :)

**Comment by manipta** [comment]
Hey idk , does u need to add the hacktober-fest label to PR? For hacktober-fest 2022

**Comment by Harsh-Singh-Rajput** [comment]
> Hey idk , does u need to add the hacktober-fest label to PR? For hacktober-fest 2022

I have linked your changes to the original issue. So it will count.

**Comment by manipta** [comment]
thanks :)

**Pull request merged**
