### PR TITLE
dark/light mode added hacktoberfest-2022

### PR DESCRIPTION
**Pull request by KedarKK1**
<ul>
<li>
Added dark/light mode functionality
</li>
<li>
Also added hovering effect to those new buttons (dark mode button & light mode button)
</li>
<li>
Combined Buttons-group in a set of 2-buttons</li>
</ul>

### CODE REVIEW

**Review by Harsh-Singh-Rajput — COMMENTED** [review]
You can add the different dark colour to the content and file area in order to distinguish them from the background colour of their parent div in both theme, 
Also there is need to change the active status of the theme button i.e when dark theme is selected then dark mode button should be in active state and vice versa for light mode

**Review by Harsh-Singh-Rajput — APPROVED** [review]
Nice work, I am merging your PR :)
Happy Hacktoberfest👍

**Comment by Harsh-Singh-Rajput** [comment]
[Code Difference](https://patch-diff.githubusercontent.com/raw/Harsh-Singh-Rajput/Notepad/pull/11.diff)

**Comment by Anikaaasingh** [comment]
@Harsh-Singh-Rajput yes pls do that for mine also

**Comment by Harsh-Singh-Rajput** [comment]
> Iss pull request ko hacktoberfest-accepted label add karde bhai varna hactoberfest me count nhi hoga mera request

Arre bhai ye maine link kr diya hai issue 9 se jisme hactoberfest ka label hai

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput yes pls do that for mine also

I will look it tomorrow

**Comment by KedarKK1** [comment]
> > Iss pull request ko hacktoberfest-accepted label add karde bhai varna hactoberfest me count nhi hoga mera request
> 
> Arre bhai ye maine link kr diya hai issue 9 se jisme hactoberfest ka label hai

Ohh achha samjha mai😋, thanks for the efforts. Baadme jab bhi time milega, to aur PR kardunga, kyuki tum acchese maintain karteho project ko. Also, I would love to collab for more such interesting projects.

**Comment by KedarKK1** [comment]
All the best👍

**Comment by Harsh-Singh-Rajput** [comment]
> > > Iss pull request ko hacktoberfest-accepted label add karde bhai varna hactoberfest me count nhi hoga mera request
> > 
> > 
> > Arre bhai ye maine link kr diya hai issue 9 se jisme hactoberfest ka label hai
> 
> Ohh achha samjha mai😋, thanks for the efforts. Baadme jab bhi time milega, to aur PR kardunga, kyuki tum acchese maintain karteho project ko. Also, I would love to collab for more such interesting projects.

Thanks👍

**Comment by Harsh-Singh-Rajput** [comment]
> All the best👍

You didn't add your name in CONTRIBUTING.md file
do the changes and make a pr

**Pull request merged**
