### PR TITLE
Adds mobile responsiveness and new supporting structure

### LINKED ISSUE #10: Want the Site to be responsive at different Screen Sizes.
You can made the the site responsive at different screen sizes like _min-width: 360px_, _min-width: 640px_, _min-width: 768px_, min-width: 1024px, min-width: 1280px etc.
- You are free to made the design as your imagination flies.
- **Multiple contributors** can create PRs but one of the best responsive designs will be selected from the Multiple PRs.

>  **Don't worry if your PR is not selected/merged there will be many more issues you can solve or create which is relevant to the repository. Learning and contributing is the key 😀. Happy Hacking....**

### PR DESCRIPTION
**Pull request by mhenrique94**
Changes: structure, added sandwich menu, icons, remodeled toolbar, minor issues.

close #10

### CODE REVIEW

**Comment by Harsh-Singh-Rajput** [comment]
@mhenrique94 I like your work but there is an issue on large screen devices like laptop or desktop 
On clicking menu bar format of text area breaks. You can see on the video.
I think there is not necessary to give menu icon on large screen since there is plenty of space to show file list and their contents.
What do you think about this?

https://user-images.githubusercontent.com/61553586/197986060-b17e7b30-2340-44de-9612-d3a69669bf1a.mp4

**Review by Harsh-Singh-Rajput — COMMENTED** [review]
@mhenrique94 I like your work but there is an issue on large screen devices like laptop or desktop
On clicking menu bar format of text area breaks. You can see on the video.
https://user-images.githubusercontent.com/61553586/197986060-b17e7b30-2340-44de-9612-d3a69669bf1a.mp4

Also I think there is not necessary to give menu icon on large screen since there is plenty of space to show file list and their contents.
What do you think about this?

**Comment by mhenrique94** [comment]
I will fix that!

**Review by Harsh-Singh-Rajput — APPROVED** [review]
Nice Work @mhenrique94 
I am merging your PR.
Happy Hactoberfest.

**Pull request merged**
